AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SessionLog - Personal trainer session management app

Globals:
  Function:
    Timeout: 30
    Runtime: python3.12
    Environment:
      Variables:
        DYNAMODB_TABLE_NAME: !Ref SessionLogTable

Resources:
  # DynamoDB
  SessionLogTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: session-log
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: exercise_member
          AttributeType: S
        - AttributeName: session_date
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: exercise-member-index
          KeySchema:
            - AttributeName: exercise_member
              KeyType: HASH
            - AttributeName: session_date
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # Lambda
  SessionLogFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/
      Handler: main.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionLogTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

  #Cognito
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: session-log-user-pool
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: session-log-client
      UserPoolId: !Ref CognitoUserPool
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/"
  TableName:
    Description: DynamoDB table name
    Value: !Ref SessionLogTable
  UserPoolId:
    Description: Cognito Userpool ID
    Value: !Ref CognitoUserPool
  ClientId:
    Description: Cognito Client ID
    Value: !Ref CognitoUserPoolClient
